'use client';
import { FormEvent, useState } from 'react';
import { useCartStore } from '@/store/cartStore';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

export default function Checkout(){
 const items=useCartStore(s=>s.items),clear=useCartStore(s=>s.clear),router=useRouter(); const [done,setDone]=useState(false); const [loading,setLoading]=useState(false); const [payment,setPayment]=useState('card'); const [orderId,setOrderId]=useState('');
 const subtotal=items.reduce((a,x)=>a+x.product.price*x.quantity,0),shipping=subtotal===0?0:subtotal>=2999?0:299,total=subtotal+shipping;
 async function pay(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!items.length)return;setLoading(true);try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items,total,payment})});const data=await r.json();if(!r.ok)throw new Error(data.message);setOrderId(data.orderId);clear();setDone(true)}finally{setLoading(false)}}
 if(done)return <main className="success-page"><div className="success-card"><div className="success-mark">✓</div><span className="eyebrow">ORDER CONFIRMED · {orderId}</span><h1>Thank you<br/><i>for choosing the drape.</i></h1><p>Your order is safely placed. We’ll prepare your selected pieces with the care they deserve and keep you updated on the journey.</p><div className="success-meta"><div><b>Delivery</b><span>Prepared with care</span></div><div><b>Payment</b><span>Mock secure checkout</span></div><div><b>Returns</b><span>7-day easy returns</span></div></div><Link href="/shop" className="luxury-cta">Continue shopping <span>↗</span></Link></div></main>;
 return <main className="checkout-page"><div className="checkout-top"><span className="eyebrow">AAVIRA CHECKOUT</span><h1>Complete your order.</h1><div className="checkout-steps"><b>01 Details</b><span>02 Payment</span><span>03 Confirmation</span></div></div>
 {!items.length?<div className="empty-cart"><span className="eyebrow">YOUR BAG IS EMPTY</span><h2>Let's find your next drape.</h2><Link href="/shop" className="luxury-cta">Browse sarees ↗</Link></div>:<section className="checkout-layout"><form className="checkout-form" onSubmit={pay}><div className="form-section"><h2>Delivery details</h2><p>Tell us where your saree should arrive.</p><div className="form-grid"><input required placeholder="Full name"/><input required type="email" placeholder="Email address"/><input required placeholder="Phone number"/><input required placeholder="PIN code"/></div><input required placeholder="Address, apartment / landmark"/><div className="form-grid"><input required placeholder="City"/><input required placeholder="State"/></div></div><div className="form-section"><h2>Payment</h2><p>Choose a mock payment method for this local build.</p><div className="payment-options">{[['card','Card'],['upi','UPI'],['cod','Cash on delivery']].map(([id,label])=><button type="button" key={id} onClick={()=>setPayment(id)} className={payment===id?'active':''}><span>{payment===id?'●':'○'}</span>{label}</button>)}</div><div className="payment-box"><span>◇</span><div><b>{payment==='card'?'Card payment':payment==='upi'?'UPI payment':'Cash on delivery'}</b><p>{payment==='cod'?'Pay when your parcel arrives.':'Mock Stripe flow — no real payment is captured in this demo.'}</p></div></div></div><button className="luxury-cta full" disabled={loading}>{loading?'Securing your order…':'Place order securely'} <span>→</span></button></form>
 <aside className="checkout-summary"><span className="eyebrow">YOUR SELECTION</span><h2>Inside the bag.</h2><div className="checkout-items">{items.map(i=><div className="checkout-item" key={i.product.id+i.color}><img src={i.product.image} alt=""/><div><b>{i.product.name}</b><span>{i.color} · Qty {i.quantity}</span><p>{i.product.description.slice(0,105)}…</p></div><strong>₹{(i.product.price*i.quantity).toLocaleString('en-IN')}</strong></div>)}</div><div className="summary-row"><span>Subtotal</span><b>₹{subtotal.toLocaleString('en-IN')}</b></div><div className="summary-row"><span>Shipping</span><b>{shipping?'₹'+shipping.toLocaleString('en-IN'):'Complimentary'}</b></div><div className="summary-total"><span>Total</span><strong>₹{total.toLocaleString('en-IN')}</strong></div><p className="secure-note">Your details are used only to process this order in the local demo.</p></aside></section>}
 </main>
}
