'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';

const slides=[
 {eyebrow:'TIMELESS HERITAGE',title:'Kanjivaram\nSilk Saree Collections',body:'A celebration of tradition, woven for your most treasured moments.',image:'/images/products/aavira-hero-saree.png',cta:'Explore Collection',href:'/shop?category=Kanjivaram'},
 {eyebrow:'THE NEW 2026 EDIT',title:'Heritage,\nwith a modern drape.',body:'A considered edit of pattu, silk, Banarasi, cotton and evening sarees.',image:'/images/products/aavira-emerald-pattu.png',cta:'Shop New Arrivals',href:'/shop?category=New%20Arrivals'}
];
export function Hero(){const [active,setActive]=useState(0);const [color,setColor]=useState('#8e1d32');const s=slides[active];useEffect(()=>{const id=setInterval(()=>setActive(v=>(v+1)%slides.length),7000);return()=>clearInterval(id)},[]);return <section className="hero-wrap"><div className="hero-stage"><div className="hero-copy"><span className="eyebrow">{s.eyebrow}</span><h1>{s.title.split('\n').map((x,i)=><span key={x} className={i===1?'accent':''}>{x}</span>)}</h1><p>{s.body}</p><div className="hero-ctas"><Link href={s.href} className="luxury-cta">{s.cta}<span>→</span></Link><Link href="#collections" className="ghost-cta">Discover the edit <span>↓</span></Link></div><div className="hero-swatches"><small>Preview palette</small>{['#8e1d32','#0f5f5a','#24365f','#c8a56b'].map(c=><button key={c} onClick={()=>setColor(c)} style={{background:c}} className={color===c?'selected':''} aria-label="Preview colour"/> )}</div><div className="hero-pagination"><b>0{active+1}</b><i/><span>0{slides.length}</span></div></div><div className="hero-image"><div className="hero-glow"/><img src={s.image} alt="AAVIRA Kanjivaram silk saree collection"/><div className="hero-image-caption"><span>PURE SILK</span><span>HANDWOVEN</span><span>TIMELESS</span></div><div className="hero-arrows"><button onClick={()=>setActive((active+slides.length-1)%slides.length)}>‹</button><button onClick={()=>setActive((active+1)%slides.length)}>›</button></div></div></div></section>}
