import Link from 'next/link';
import { products } from '@/data/products';
import { ProductCard } from '@/components/product/ProductCard';

const weaves=[['Kanjivaram','Heritage','/shop?category=Kanjivaram','/images/products/01_kanchipuram_silk.png'],['Pattu','Bridal silk','/shop?category=Pattu','/images/products/06_wedding_silk.png'],['Silk','Timeless','/shop?category=Silk','/images/products/03_tissue_silk.png'],['Banarasi','Woven stories','/shop?category=Banarasi','/images/products/02_banarasi_silk.png'],['Cotton','Everyday','/shop?category=Cotton','/images/products/12_handloom_cotton.png']];
const occasions=[['Weddings','Heirloom dressing','/shop?occasion=Wedding','/images/products/06_wedding_silk.png'],['Festive','Luminous celebrations','/shop?occasion=Festive','/images/products/03_tissue_silk.png'],['Party Wear','After dark','/shop?category=Party%20Wear','/images/products/05_pure_zari_silk.png'],['Everyday','Quiet luxury','/shop?occasion=Everyday','/images/products/12_handloom_cotton.png']];

export function Featured(){
 const newArrivals=products.filter(p=>p.newArrival).slice(0,6); const trending=products.filter(p=>p.featured).filter(p=>!newArrivals.some(n=>n.id===p.id)).slice(0,4);
 return <>
  <section className="benefit-strip"><div><b>Authentic Pure Silks</b><span>Certified & considered</span></div><div><b>Complimentary Shipping</b><span>On orders above ₹2,999</span></div><div><b>Easy Returns</b><span>Hassle-free 7 days</span></div><div><b>Secure Payments</b><span>100% protected</span></div></section>
  <section id="collections" className="content-section compact-top"><div className="section-head"><div><span className="eyebrow">SHOP BY WEAVE</span><h2>Find your silk.</h2></div><Link href="/shop">View all ↗</Link></div><div className="visual-category-grid">{weaves.map(([label,sub,href,img])=><Link href={href} key={label} className="visual-category-card"><img src={img} alt=""/><div><h3>{label}</h3><span>{sub}</span></div><b>↗</b></Link>)}</div></section>
  <section className="content-section occasion-section"><div className="section-head"><div><span className="eyebrow">SHOP BY OCCASION</span><h2>Dress for the moment.</h2></div><Link href="/shop">Explore occasions ↗</Link></div><div className="occasion-links">{occasions.map(([label,sub,href,img])=><Link href={href} key={label} className="occasion-link"><img src={img} alt=""/><span><b>{label}</b><small>{sub}</small></span><i>↗</i></Link>)}</div></section>
    <section className="editorial-banner"><div className="editorial-copy"><span className="eyebrow">KANJIVARAM SILK COLLECTIONS</span><h2>Woven for<br/><i>generations.</i></h2><p>Rich silk, intricate zari and timeless South Indian craft, curated for weddings and heirloom moments.</p><Link href="/shop?category=Kanjivaram" className="light-cta">Explore Kanjivaram ↗</Link></div><div className="editorial-image"><img src="/images/products/01_kanchipuram_silk.png" alt="Kanjivaram textile artwork"/></div></section>
  <section className="content-section compact-top"><div className="section-head"><div><span className="eyebrow">THE LATEST EDIT</span><h2>New arrivals.</h2></div><Link href="/shop?category=New%20Arrivals">View all ↗</Link></div><div className="product-grid">{newArrivals.map(p=><ProductCard key={p.id} p={p}/>)}</div></section>
    <section className="story-banner"><div className="story-banner-image"><img src="/images/products/04_soft_silk.png" alt="Silk textile detail"/></div><div><span className="eyebrow">TRENDING KANJIVARAM SAREES</span><h2>Colour stories<br/><i>for the season.</i></h2><p>From temple borders to modern jewel tones, discover the pieces becoming part of the new AAVIRA wardrobe.</p><Link href="/shop?category=Kanjivaram" className="luxury-cta">Shop trending sarees <span>→</span></Link></div></section>
  <section className="content-section compact-top"><div className="section-head"><div><span className="eyebrow">MOST LOVED</span><h2>Considered favourites.</h2></div><Link href="/shop">View collection ↗</Link></div><div className="product-grid">{trending.map(p=><ProductCard key={p.id} p={p}/>)}</div></section>
    <section className="promo-grid"><Link href="/shop?category=Pattu" className="promo-card"><img src="/images/products/06_wedding_silk.png" alt="Bridal pattu"/><div><span>WEDDING COLLECTION</span><h3>Bridal Pattu</h3><p>For your most special day.</p><b>Explore ↗</b></div></Link><Link href="/shop?category=Party%20Wear" className="promo-card"><img src="/images/products/05_pure_zari_silk.png" alt="Party wear"/><div><span>AFTER DARK</span><h3>Party Wear</h3><p>Make an entrance.</p><b>Shop now ↗</b></div></Link><Link href="/shop?category=Designer" className="promo-card"><img src="/images/products/04_soft_silk.png" alt="Designer saree"/><div><span>THE MODERN MUSE</span><h3>Designer Edit</h3><p>Contemporary, considered, unforgettable.</p><b>Discover ↗</b></div></Link></section>
 </>;
}
export function Story(){return <section id="story" className="story-section"><div className="story-inner"><span className="eyebrow">THE AAVIRA PHILOSOPHY</span><h2>Not just a saree.<br/><i>A memory in the making.</i></h2><p>Every AAVIRA edit is designed around luminous silk, thoughtful colour and considered detail — an experience that feels as special as the occasion.</p><Link href="/shop" className="light-cta">Enter the atelier ↗</Link></div></section>}
