'use client';
import { Suspense, useEffect, useMemo, useState } from 'react';
import { products, categories, occasions } from '@/data/products';
import { ProductCard } from '@/components/product/ProductCard';
import { useSearchParams, useRouter, usePathname } from 'next/navigation';

const resolveCategory=(value:string|null)=>{const match=categories.find(c=>c.toLowerCase()===(value||'all').toLowerCase());return match||'All'};

function ShopContent(){
 const params=useSearchParams();const router=useRouter();const pathname=usePathname();
 const [cat,setCat]=useState<string>(()=>resolveCategory(params.get('category')));const [occasion,setOccasion]=useState(params.get('occasion')||'All');const [sort,setSort]=useState('featured');const [max,setMax]=useState(35000);const [query,setQuery]=useState('');const [filtersOpen,setFiltersOpen]=useState(false);
 // keep filter state synced when the URL changes without a full remount (e.g. clicking a category link while already on /shop)
 useEffect(()=>{setCat(resolveCategory(params.get('category')))},[params]);
 const list=useMemo(()=>products.filter(p=>{const categoryOk=cat==='All'||(cat==='New Arrivals'?!!p.newArrival:p.category.toLowerCase()===cat.toLowerCase());const occasionOk=occasion==='All'||(p.occasion||'').toLowerCase().includes(occasion.toLowerCase());const text=`${p.name} ${p.fabric} ${p.category} ${p.collection} ${p.occasion}`.toLowerCase().includes(query.toLowerCase());return categoryOk&&occasionOk&&p.price<=max&&text}).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:(Number(b.featured)-Number(a.featured))||(Number(b.newArrival)-Number(a.newArrival))||a.price-b.price),[cat,occasion,sort,max,query]);
 const choose=(c:string)=>{setCat(c);setFiltersOpen(false);const sp=new URLSearchParams(params.toString());if(c==='All'){sp.delete('category')}else{sp.set('category',c)}router.replace(sp.toString()?`${pathname}?${sp.toString()}`:pathname,{scroll:false})};
 return <main className="shop-page"><section className="shop-hero"><div><span className="eyebrow">THE AAVIRA COLLECTION</span><h1>Find the saree<br/><i>you'll remember.</i></h1><p>Browse by weave, occasion and price. Every edit is curated to make the choice feel as considered as the saree itself.</p></div><div className="shop-hero-stat"><strong>{products.length}</strong><span>pieces in the edit</span><small>New designs added regularly</small></div></section>
 <section className="shop-controls"><div className="shop-control-top"><div className="category-scroll"><button className={cat==='All'?'active':''} onClick={()=>choose('All')}>All</button>{categories.filter(c=>c!=='All').map(c=><button key={c} className={cat===c?'active':''} onClick={()=>choose(c)}>{c}</button>)}</div><div className="shop-tools"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search sarees, colours…"/></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option></select></label><button className="filter-toggle" onClick={()=>setFiltersOpen(v=>!v)}>Filters {filtersOpen?'−':'+'}</button></div></div>
 <div className={`filter-panel ${filtersOpen?'open':''}`}><div><span className="filter-label">Occasion</span><div className="filter-chips"><button className={occasion==='All'?'active':''} onClick={()=>setOccasion('All')}>All</button>{occasions.map(o=><button key={o} className={occasion===o?'active':''} onClick={()=>setOccasion(o)}>{o}</button>)}</div></div><div className="price-filter"><div><span className="filter-label">Price</span><b>Up to ₹{max.toLocaleString('en-IN')}</b></div><input type="range" min="5000" max="35000" step="500" value={max} onChange={e=>setMax(Number(e.target.value))}/></div><button className="reset-filter" onClick={()=>{setCat('All');setOccasion('All');setMax(35000);setQuery('');setSort('featured')}}>Reset all</button></div></section>
 <div className="shop-result-head"><div><span className="eyebrow">{cat==='All'?'ALL EDITS':cat.toUpperCase()}</span><p>{list.length} pieces</p></div><span>{occasion==='All'?'Every occasion':occasion}</span></div><section className="product-grid shop-grid">{list.map(p=><ProductCard key={p.id} p={p}/>)}</section>{!list.length&&<div className="empty-state"><h2>No exact match.</h2><p>Try another category, occasion or a wider price range.</p><button className="light-cta" onClick={()=>{setCat('All');setOccasion('All');setMax(35000);setQuery('')}}>Reset filters ↗</button></div>}</main>
}
export default function Shop(){return <Suspense fallback={<main className="shop-page"><div className="loading-card"/></main>}><ShopContent/></Suspense>}
